JrAuLouvre/force-app/main/default/objects/public_voluntary__x/public_voluntary__x.object-meta.xml
<CustomObject>
    <description>public$voluntary</description>
    <externalDataSource>herokudb</externalDataSource>
    <externalName>public$voluntary</externalName>
    <label>public$voluntary</label>
    <pluralLabel>public$voluntary</pluralLabel>
</CustomObject>

JrAuLouvre/force-app/main/default/objects/public_voluntary__x/fields/confirmationcode__c.field-meta.xml
<CustomField>
    <fullName>confirmationcode__c</fullName>
    <description>confirmationcode</description>
    <externalDeveloperName>confirmationcode</externalDeveloperName>
    <label>confirmationcode</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

JrAuLouvre/force-app/main/default/objects/public_voluntary__x/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <description>email</description>
    <externalDeveloperName>email</externalDeveloperName>
    <label>email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

JrAuLouvre/force-app/main/default/objects/public_voluntary__x/fields/firstname__c.field-meta.xml
<CustomField>
    <fullName>firstname__c</fullName>
    <description>firstname</description>
    <externalDeveloperName>firstname</externalDeveloperName>
    <label>firstname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

JrAuLouvre/force-app/main/default/objects/public_voluntary__x/fields/id__c.field-meta.xml
<CustomField>
    <fullName>id__c</fullName>
    <description>id</description>
    <externalDeveloperName>id</externalDeveloperName>
    <label>id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

JrAuLouvre/force-app/main/default/objects/public_voluntary__x/fields/lastname__c.field-meta.xml
<CustomField>
    <fullName>lastname__c</fullName>
    <description>lastname</description>
    <externalDeveloperName>lastname</externalDeveloperName>
    <label>lastname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

JrAuLouvre/force-app/main/default/objects/public_voluntary__x/fields/registrationstatus__c.field-meta.xml
<CustomField>
    <fullName>registrationstatus__c</fullName>
    <description>registrationstatus</description>
    <externalDeveloperName>registrationstatus</externalDeveloperName>
    <label>registrationstatus</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

JrAuLouvre/force-app/main/default/objects/public_voluntary__x/fields/shiftid__c.field-meta.xml
<CustomField>
    <fullName>shiftid__c</fullName>
    <description>shiftid</description>
    <externalDeveloperName>shiftid</externalDeveloperName>
    <label>shiftid</label>
    <length>36</length>
    <referenceTo>public_shift__x</referenceTo>
    <relationshipLabel>public$voluntary</relationshipLabel>
    <relationshipName>public_voluntary</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

JrAuLouvre/force-app/main/default/objects/public_voluntary__x/fields/telephone__c.field-meta.xml
<CustomField>
    <fullName>telephone__c</fullName>
    <description>telephone</description>
    <externalDeveloperName>telephone</externalDeveloperName>
    <label>telephone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-side/apex/ContactSearch2.cls
public class ContactSearch2 {

    @AuraEnabled
    public static List<public_voluntary__x > getContacts(String theCode) {
        if (theCode == null || theCode == '') {
       return [Select id__c , firstname__c , lastname__c , email__c , telephone__c , confirmationcode__c , shiftid__c , registrationstatus__c  From public_voluntary__x order by lastname__c  asc limit 10];     
        } else {
       return [Select id__c , firstname__c , lastname__c , email__c , telephone__c , confirmationcode__c , shiftid__c , registrationstatus__c  From public_voluntary__x  Where confirmationcode__c  LIKE : (theCode + '%') OR lastname__c  LIKE : (theCode + '%') OR firstname__c  LIKE : (theCode + '%') order by lastname__c  asc limit 10];
        }
    }
    
	@future(callout=True)
    public static void asyncCallout(String uid, String value)
    {
        public_externalobjectdemo__x obj = new public_externalobjectdemo__x(id__c = uid, val__c=value);
        System.debug(obj.id__c);
        System.debug(obj.val__c);
        Database.SaveResult srList2 = Database.insertAsync(obj);
    }
    
    @AuraEnabled
    public static void checkinContacts(string contactId){
        try{
            public_voluntary__x objCon=[Select id__c , firstname__c , lastname__c , email__c , telephone__c , confirmationcode__c , shiftid__c , registrationstatus__c  From public_voluntary__x where id__c=:contactId limit 1];
            if(objCon !=null){
                if(objCon.registrationstatus__c == 'CONFIRMED') {
                	objCon.registrationstatus__c = 'COMPLETED';
                } else {
                    objCon.registrationstatus__c = 'CONFIRMED';
                }
				Database.SaveResult srList2 = Database.updateAsync(objCon);
            }
            
        }
        catch(Exception ex){}
    } 
}